name: main
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: yarn install
    - run: yarn build
      env: 
        REACT_APP_WEB3STORAGE_KEY: ${{ secrets.WEB3STORAGE_KEY }}
    - name: Upload to IPFS
      uses: aquiladev/ipfs-action@v0.1.6-1
      id: upload
      with:
        path: ./build
        service: pinata
        pinataKey: ${{ secrets.PINATA_KEY }}
        pinataSecret: ${{ secrets.PINATA_SECRET }}
        pinataPinName: deChess
    - name: Deploy to Skynet
      uses: SkynetLabs/deploy-to-skynet-action@v2.0.1
      with:
        upload-dir: ./build
        github-token: ${{ secrets.GITHUB_TOKEN }}
        registry-seed: ${{ secrets.SKYNET_REGISTRY_SEED || '' }}
        
