name: main
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.13.1'
    - run: yarn install
    - run: yarn build
      env: 
        REACT_APP_WEB3STORAGE_KEY: ${{ secrets.WEB3STORAGE_KEY }}
        REACT_APP_COVALENT_API_KEY: ${{ secrets.REACT_APP_COVALENT_API_KEY }}
        REACT_APP_MORALIS_APPLICATION_ID: ${{ secrets.REACT_APP_MORALIS_APPLICATION_ID }}
        REACT_APP_MORALIS_SERVER_URL: ${{ secrets.REACT_APP_MORALIS_SERVER_URL }}
        REACT_APP_NFTSTORAGE_KEY: ${{ secrets.REACT_APP_NFTSTORAGE_KEY }}
    - name: Upload to IPFS
      uses: aquiladev/ipfs-action@v0.1.6-1
      id: upload
      with:
        path: ./build
        service: pinata
        pinataKey: ${{ secrets.PINATA_KEY }}
        pinataSecret: ${{ secrets.PINATA_SECRET }}
        pinataPinName: deChess
        
